### ISSUE TITLE
[Conflict] Fail to run

### ISSUE THREAD

**Issue by javirst** [mogery/memhop#1]
Unable to run when used together with NWG & NWD
_https://github.com/gabdube/native-windows-gui_

> error: process didn't exit successfully: `target\debug\test.exe` (exit code: 0xc0000139, STATUS_ENTRYPOINT_NOT_FOUND)

**Comment by mogery** [comment]
My guess would be that NWG's `winapi` and memhop's `windows` crate are clashing. Unfortunately I have no clue how to solve this for now. :(

**Comment by javirst** [comment]
Yeah it's coming from NWG's.
https://github.com/gabdube/native-windows-gui/issues/251

I think it's fine to close this.
